# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarms',
            name='alarm_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u62a5\u8b66\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='process_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5904\u7406\u4eba'),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='process_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5904\u7406\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='process_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5904\u7406\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='alarms',
            name='report_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u62a5\u8b66\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='acreage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u670d\u52a1\u9762\u79ef'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='create_date',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='\u5efa\u7acb\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='creator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='cxc_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4ea7\u9500\u5dee\u76ee\u6807\u503c'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='dma_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u5206\u533a\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='ifc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='IFC\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='night_use',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6b63\u5e38\u591c\u95f4\u7528\u6c34\u91cf'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='pepoles_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u670d\u52a1\u4eba\u53e3'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='pipe_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ba1\u9053\u603b\u957f\u5ea6(m)'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='pipe_links',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ba1\u9053\u8fde\u63a5\u603b\u6570(\u4e2a)'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='pipe_private',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u79c1\u4eba\u62e5\u6709\u6c34\u7ba1\u957f\u5ea6(m)'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='pipe_texture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ba1\u9053\u6750\u8d28'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='pipe_years',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ba1\u9053\u6700\u957f\u670d\u52a1\u5e74\u9650(\u5e74)'),
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='user_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u6237\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='base_power',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u57fa\u8868\u7535\u91cf%'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='comm_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='instance_flow',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u77ac\u65f6\u6d41\u91cfm\xb3/h'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='postive_flow',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6b63\u5411\u6d41\u91cfm\xb3'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='read_interval',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u91c7\u6837\u95f4\u9694min'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='read_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6700\u65b0\u91c7\u6837\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='report_interval',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4e0a\u62a5\u95f4\u9694h'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='reverse_flow',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u53cd\u5411\u6d41\u91cfm\xb3'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='signals',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4fe1\u53f7\u5f3a\u5ea6%'),
        ),
        migrations.AlterField(
            model_name='meterflow',
            name='trans_power',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8fdc\u4f20\u7535\u91cf%'),
        ),
        migrations.AlterField(
            model_name='meterpress',
            name='press',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u538b\u529bMpa'),
        ),
        migrations.AlterField(
            model_name='meterpress',
            name='read_interval',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u91c7\u6837\u95f4\u9694min'),
        ),
        migrations.AlterField(
            model_name='meterpress',
            name='read_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6700\u65b0\u91c7\u6837\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='meterpress',
            name='report_interval',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4e0a\u62a5\u95f4\u9694h'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='dma.Organization', verbose_name='\u6240\u5c5e\u7ec4\u7ec7'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='big_user',
            field=models.BooleanField(max_length=50, verbose_name='\u5927\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='caliber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u53e3\u5f84'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='focus',
            field=models.BooleanField(max_length=50, verbose_name='\u91cd\u70b9\u5173\u6ce8'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='geopos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4f4d\u7f6e\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='installed',
            field=models.DateField(blank=True, verbose_name='\u5b89\u88c5\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ecf\u5ea6'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='meter_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8868\u5177\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='meter_property',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7528\u6c34\u6027\u8d28'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='meter_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8868\u5177\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='simno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SIM\u5361\u53f7'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='station_desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7ad9\u70b9\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='station_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u7ad9\u70b9\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='station_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u7c7b\u578b'),
        ),
    ]
