# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dma', '0004_auto_20180528_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='\u7ec4\u7ec7\u673a\u6784\u540d\u79f0')),
                ('attribute', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7ec4\u7ec7\u673a\u6784\u6027\u8d28')),
                ('register_date', models.DateField(blank=True, max_length=300, null=True, verbose_name='\u6ce8\u518c\u65e5\u671f')),
                ('owner_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u8d1f\u8d23\u4eba')),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('firm_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5730\u5740')),
                ('cid', models.CharField(blank=True, max_length=300, null=True)),
                ('pId', models.CharField(blank=True, max_length=300, null=True)),
                ('is_org', models.BooleanField(max_length=300)),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': True,
            },
        ),
    ]
